### ISSUE TITLE
Docker files become very large 

### ISSUE THREAD

**Issue by beshoo** [mattes/rotating-proxy#50]
Hi.

I set the tor to fork 50 processes so I can have 50 open ports.
The problem, the docker log file takes more than 80% of the server space! the total space is 917G, and the docker files are around 700 GB!
WAW. ps the docker has only once running container. which is **rotating-proxy**
even cleaning Docker dos not help. the only way to reclaim the wasting space is by uninstalling the docker and deleting the docker folder altogether.

Please advice

**Comment by stevet11** [comment]
This is a docker issue.  See https://docs.docker.com/engine/logging/configure/ for possible fixes.

You can change the docker daemon - system wide, or configure it per container.

Configuring for one service in docker-compose.yaml:

```yaml
services:
  proxy:
    ... existing lines ...
    logging:
    driver: "json-file"
      options:
        max-file: "5"
        max-size: "16m"
```

This would have a log for your container with max size 16MB.  Having huge log files fills up the drive, and makes ```docker-compose logs``` scroll for awhile.
